name: Pull Request
description: Pull request template for code contributions
title: "[PR]: "
labels: ["pull-request"]
assignees:
  - APrettyCoolProgram
body:
  - type: dropdown
    id: pr-type
    attributes:
      label: Pull Request Type
      description: What type of pull request is this?
      options:
        - Development
        - Documentation Update
        - Stable Release
        - Commuity Release
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        A *Development* pull request is for ongoing work that may not be stable.
        A *Documentation Update* pull request is for changes that only affect documentation.
        A *Stable Release* pull request is for changes that are intended for a stable release.
        A *Community Release* pull request is for changes contributed by the community.
  - type: textarea
    id: pr-description
    attributes:
      label: Pull Request description
      description: Provide a brief description of the changes made in this pull request.
    validations:
      required: true
