name: Documentation issue
description: Give feedback about documentation
title: "[DOC]: "
labels: ["documentation"]
assignees: ["aprettycoolprogram"]
body:
  - type: markdown
    attributes:
      value: |

  - type: textarea
    id: bug-description
    attributes:
      label: Feedback
      description: Give feedback about the documentation
    validations:
      required: true